config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get "recipes" =>"recipes#index"
  root 'recipes#index'
  resources :recipes do
  resources :comments
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	
validates :name, :rating, :comment, presence:true
validates_length_of :comment, maximum:200
RATING=[0,1,2,3,4,5] 
validates_inclusion_of :rating, in: RATING

  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	validates :name, :stuff, :duration, :prepare_mode, presence:true
	validates_length_of :stuff, maximum: 200
	validates_length_of :prepare_mode, maximum: 300
	validates_numericality_of :calories, greater_than_or_equal_to:0, presence:true
	validates_format_of :poster, allow_blank:true,  with: /\w+\.(png|gif|jpg)\z/i, message: " Utilizar somente arquivos GIF, JPG E PNG."
	
	KIND = %W(Carnes Bolos Peixes Massas Salgados Doces)
	validates_inclusion_of :kind , in: KIND

	has_many :comments, dependent: :destroy

	def light?
		calories.blank? || calories < 100
	end

	def self.created_at
		where('created_at <= ?', Time.now).order('created_at desc')
		
	end

	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #before_action :set_recipe, only:new , except: destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_recipe

	def index
		#@recipe = Recipe.find(params[:recipe_id])
		@comments = @recipe.comments
		
	end

	def new
		#@recipe = Recipe.find(params[:recipe_id])
		@comment = @recipe.comments.new
	end

	def create
		#@recipe = Recipe.find(params[:recipe_id])
		@comment = @recipe.comments.new(comment_params)
		if @comment.save
			redirect_to recipe_comments_path(@recipe), notice:'Comentário gravado com Sucesso!'
		else
			render :new
		end
		
	end

	private
	def comment_params
		params.require(:comment).permit(:name, :comment , :rating)
	end

	def set_recipe
		@recipe = Recipe.find(params[:recipe_id])
		
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	def index
	@recipes = Recipe.created_at
	end


	def show
		@recipe = Recipe.find(params[:id])
	end

	def edit
		@recipe = Recipe.find(params[:id])
	end

	def update
		@recipe = Recipe.find(params[:id])
		
		if @recipe.update(recipe_params)
		redirect_to @recipe, notice: "Receita alterada com Sucesso!"
	else
		render :edit
	end
	end

	def new

		@recipe = Recipe.new
	end

	def create
		#recipe_params = params.require(:recipe).permit!
		@recipe = Recipe.new(recipe_params)
		if 
			@recipe.save
			
			redirect_to @recipe, notice: "Receita criada com Sucesso!"
		else
			render :new
		end
		
		end

	def destroy
	@recipe = Recipe.find(params[:id])	
	@recipe.destroy
	redirect_to recipes_url, alert: "Receita Deletada com Sucesso!"
		else

	end

	private
	def recipe_params
		recipe_params = params.require(:recipe).permit(:name, :stuff, :calories, :prepare_mode, :cost, :kind, :portion, :duration, :poster  )
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
	def formata_caloria(recipe)
		if recipe.light?
			content_tag(:strong, "Light (Menos de 100 Calorias)")
		else
		recipe.calories
		end 
	end

	def image(recipe)
		if recipe.poster.blank?
			image_tag('sem_imagem.png')
		else
			image_tag(recipe.poster)
		end
	
	end
end

app/views/comments/_form.html.erb
<%= form_for([@recipe, @comment]) do |f| %>

<%= render 'layouts/errors', object:@comment %>

<p class="form-group">
	 <%= f.label :Nome %><br/>
	 <%= f.text_field :name, autofocus: true, class:"form-control" %>
</p>

<p class="form-group">
	 <%= f.label :Estrelas %><br/>
	 <%= f.select :rating, Comment::RATING , prompt: 'Escolha a quantidade de Estrelas' , class:"form-control" %>
</p>

<p class="form-group">
	 <%= f.label :Comentário %><br/>
	 <%= f.text_area :comment, placeholder: "Escreva o seu comentário...", class:"form-control" %>
</p>

<p>
	 <%= f.submit class:'btn btn-primary' %>
	 <%= link_to 'Cancelar' , root_path , class:'btn btn-danger'%>
</p>


<%end%>

app/views/comments/index.html.erb
<div class="container">

	<% if @comments.size>0 %>

	<div class="jumbotron">
		<ul>
			<% @comments.each do|comment| %>
			<li>
				<p>
					<%= comment.name %><br>
					<small class="small_font_rating"><%= pluralize(comment.rating, 'Estrela', 'Estrelas') %></small> <small class="small_font"> - <%= time_ago_in_words(comment.created_at) %> atrás</small>
				</p>

				<p>
					<%=comment.comment %>
				</p>
			</li>
			<% end %>
		</ul>
	</div>

	<% else %>

	<div class="jumbotron">
	<h3>Não existem comentários para esta Receita!</h3>
	</div>
<% end %>

	<%= link_to recipes_path , class:'btn-link' do %>
	<i class="glyphicon glyphicon-home">Receitas</i>
	<%end%>
</div>

app/views/comments/new.html.erb
<div class="container">
	<div class="panel panel-primary">
		
		<div class="panel-heading">
			<h2>Criando novo Comentário</h2>
		</div>

		<div class="panel-body">
			<%= render 'form' %>
		</div>

	</div>
	
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any?  %>
	<div class="alert alert-danger" role="alert">
		<ul>
			<% object.errors.full_messages.each do |message| %>
				<li> <%= message %> </li>
		<%end%> 
		</ul>
	</div>
<%end%>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  
  <div class="container">
      
      <div class="alert alert-success alert-dismissible" role="alert">
         <button type="button" class="close" data-dismiss="alert" aria-label="close">
            <span aria-hidden="true">&times;</span>
         </button>
            <%= flash[:notice] %>
      </div>

  </div>

  <% elsif flash[:alert] %>

  <div class="container">
      
      <div class="alert alert-danger alert-dismissible" role="alert">
         <button type="button" class="close" data-dismiss="alert" aria-label="close">
            <span aria-hidden="true">&times;</span>
         </button>
            <%= flash[:alert] %>
      </div>

  </div>

<%end%>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark container-fluid">
  		<% link_to image_tag( 'logo.png', size: '30', alt: 'Receitasnet'), root_path, class: 'navbar-brand' %>
      <%= link_to 'Receitasnet', root_path, class: 'navbar-brand'  %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Receitasnet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>

        <%= render 'layouts/flash' %>

    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>

<%= render 'layouts/errors', object:@recipe %>

<p class="form-group">
	<%= f.label :Nome  %><br>
	<%= f.text_field :name , class:"form-control"%>
</p>
<p class="form-group">
	<%= f.label :Ingredientes  %><br>
	<%= f.text_area :stuff, cols:20 , rows:5 , class:"form-control" %>
</p>

<p class="form-group">
	<%= f.label :Tipo  %><br>
	<%= f.select :kind , Recipe::KIND , prompt: 'Escolha sua opção',  class:"form-control" %>
</p>

<p class="form-group">
	<%= f.label :Calorias  %><br>
	<%= f.number_field :calories , class:"form-control" %>
</p>

<p class="form-group">
	<%= f.label :Modo_de_Preparo  %><br>
	<%= f.text_area :prepare_mode, cols:20 , rows:5 , class:"form-control" %>
</p>

<p class="form-group">
	<%= f.label :Tempo_de_preparo  %><br>
	<%= f.time_select :duration , class:"form-control" %>
</p>

<p class="form-group">
	<%= f.label :Porções  %><br>
	<%= f.text_field :portion , class:"form-control" %>
</p>

<p class="form-group">
	<%= f.label :Poster  %><br>
	<%= f.file_field :poster, placeholder: "GIF, JPG, JPG, ou PNG" , class:"form-control"%>
</p>

<p class="form-group">
	<%= f.label :Custo  %><br>
	<%= f.number_field :cost , class:"form-control" %>
</p>

<p>
	<%= f.submit class:"btn btn-primary" %>
	<%= link_to 'Cancelar', root_path, class:"btn btn-danger" %>
</p>
<% end %>

app/views/recipes/edit.html.erb
<div class="container">

<div class="panel panel-primary">
	<div class="panel-heading">
		<h2>Editando Receita</h2>
		
	</div>

	<div class="panel-body">

		<%= render 'form' %>
		
	</div>
	
</div>

</div>

app/views/recipes/index.html.erb
<div class="container">
<h1> <%= pluralize(@recipes.count, 'Receita', 'Receitas') %></h1>
<small class="nova_receita"> <%= link_to 'Nova Receita' , new_recipe_path %> </small>


	<% @recipes.each do |recipe| %>
	<article>
		<header>
		<h2><%= link_to recipe.name , recipe %></h2>
			<%= image(recipe) %>
		</header>
		<p>
			<%= truncate(recipe.stuff, length:15, separator: ' ' ) %>
		</p>

	   <p>
	   	   <%= formata_caloria(recipe) %>
	   </p>
	   <strong>Tempo de Preparo</strong>
	   <p>
	   	<%= recipe.duration.to_formatted_s(:time) %> Min
	   </p>
	 <table>
	 	<tr>
	 		<th>Modo de Preparo</th>
	 		<td><%=recipe.prepare_mode %></td>
	 	</tr>
	 	<tr>
	 		<th>Custo do Prato</th>
	 		<td><%= number_to_currency(recipe.cost) %></td>

	 	</tr>


	 </table>
	
	
	<% end %>
	</article>

<br>


</div>

app/views/recipes/new.html.erb
<div class="container">

<div class="panel panel-primary">
	<div class="panel-heading">
		<h2>Criando Novas Receitas</h2>
		
	</div>

	<div class="panel-body">

		<%= render 'form' %>
		
	</div>
	
</div>

</div>

app/views/recipes/show.html.erb
<div class="container">
<div class="jumbotron">
<article>
	<header>
		<h1><%= @recipe.name %></h1>	
		<%= image(@recipe) %>
	</header>
	<h2>Tipo</h2>
	<p>
		<%= @recipe.kind %>
	</p>

<h2>Ingredientes</h2>
	<p>
		<%= @recipe.stuff %>
	</p>
	<h2>Calorias</h2>
	 <p> <%= @recipe.calories %></p>

	<h3>Modo de Preparo</h3>
	<p>
		<%= @recipe.prepare_mode %>
	</p>

	<h3>Tempo de Preparo</h3>
	<p>
		<%= @recipe.duration.to_formatted_s(:time) %> min
	</p>
	<h3>Porções</h3>
	<p>
		<%= pluralize(@recipe.portion, 'Porção', 'Porções') %>
	</p>

	<h3>Custo</h3>
		<p><%= @recipe.cost %></p>

</article>
<%= link_to pluralize(@recipe.comments.size, 'Comentário', 'Comentários'), recipe_comments_path(@recipe) %>
<%= link_to "Novo Comentário", new_recipe_comment_path(@recipe), class: 'btn btn-primary' %>
</div>

<%= link_to recipes_path , class:'btn-link' do %>
<i class="glyphicon glyphicon-home">Receitas</i>
<%end%>

<%= link_to edit_recipe_path(@recipe), class:'btn-link' do %>
<i class="glyphicon glyphicon-edit">Editar</i>
<%end%>


<%= link_to recipe_path(@recipe), method: :delete, data:{ confirm: "Deseja deletar esta Receita?"},  class:'btn-link' do %>

<i class="glyphicon glyphicon-remove-sign">Deletar</i>
<%end%>


</div>